# import asyncio
# from sqlalchemy import select
# from sqlalchemy.ext.asyncio import AsyncSession
# from app.core.db import async_session
# from app.modules.iam.models.user import User
# from app.modules.iam.security.passwords import hash_password
# import uuid
#
#
# async def seed_admin():
#     async with async_session() as session:  # type: AsyncSession
#
#         existing = await session.scalar(
#             select(User).where(User.username == "admin")
#         )
#
#         if existing:
#             print("Admin user already exists:", existing.user_id)
#             return
#
#         admin = User(
#             user_id=uuid.uuid4(),
#             username="admin",
#             profile_id="admin-profile-1",
#             auth_key="autogenerated-auth-key",
#             password_hash=hash_password("@dmiN123"),
#             status=10,
#         )
#
#         session.add(admin)
#         await session.commit()
#         print("Admin user created:", admin.user_id)
#
#
# if __name__ == "__main__":
#     asyncio.run(seed_admin())
